version: '3'

services:
  franka_ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${UID:-1001}
        - USER_GID=${UID:-1001}
    container_name: franka_ros2
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./limits.conf:/etc/security/limits.conf
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    user: ${UID:-1001}:${UID:-1001}
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
