services:
  ros2_control:
    build: .
    container_name: franka_ros2
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../:/franka_ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:$XAUTHORITY
      - ./limits.conf:/etc/security/limits.conf
      - ~/.gitconfig:/etc/gitconfig:ro
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
      - http_proxy=
      - https_proxy=
    user: user:user
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    #           count: all